spring:
  application:
    name: gis-service
  config:
    import: optional:configserver:http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus